fish_plugins:
  - dracula/fish                # Dracula theme which influences the colors of what you type
  - halostatue/fish-docker      # Docker and docker-compose completions
  - jethrokuan/z                # Pure-fish z directory jumping
  - laughedelic/pisces          # Plugin to help you work with paired symbols
