homebrew_formulae:
  - less # required for bat to have the latest version of less as its pager
  - imagemagick # for "magick" tool
  - poppler # for "pdfunite" and "pdfseparate" tools
  - pandoc # for typora's export functionality

  - ali
  - ansible
  - awscli
  - bat
  - cloudflared
  - dust
  - eza
  - fd
  - ffmpeg
  - fish
  - flyctl
  - git
  - git-extras
  - httpie
  - jq
  - magic-wormhole
  - mkcert
  - node@22
  - p7zip
  - parallel
  - pipx
  - postgresql@16
  - pre-commit
  - python@3.12
  - rename
  - ripgrep
  - ruby
  - ruff
  - sd
  - starship
  - trash
  - watchman
  - yt-dlp

homebrew_casks:
  - font-fira-mono-nerd-font # required for starship

  - 1password
  - 1password-cli
  - alcove
  - anydesk
  - bartender
  - basecamp
  - coconutbattery
  - cyberduck
  - docker-desktop
  - dropbox
  - fantastical
  - fork
  - google-chrome
  - httpie-desktop
  - iina
  - iterm2
  - karabiner-elements
  - loom
  - nordvpn
  - numi
  - postico
  - rectangle
  - redis-insight
  - slack
  - sublime-text
  - the-unarchiver
  - ticktick
  - transmission
  - typora
  - visual-studio-code
  - whatsapp
  - zoom
